before_script: &before_script_all
  - cat /etc/*-release
  - if [ -x "$(command -v go)" ]; then go version; fi;
  - if [ -n "$APT_GET" ]; then apt-get update -qq -y; apt-get install -qq -y --no-install-recommends $APT_GET; fi;
  - if [ -n "$DISPLAY" ]; then Xvfb $DISPLAY -screen 0 1024x768x24 & fi;

golang-gtk-modules:
  image: "golang:${GOVERSION}"
  stage: build
  variables:
    DISPLAY: ":1"
    APT_GET: "libgtk-3-dev xvfb"
  script:
    - go build -v . ./example/...
    - go test -v ./base ./loop ./dialog .
  parallel:
    matrix:
      - GOVERSION: ["1.11", "1.12", "1.13", "1.14", "1.15", "1.16", "1.17"]
        DUMMY: ["dummy"]

golang-gtk-gopath:
  image: "golang:${GOVERSION}"
  stage: build
  variables:
    GOPATH: $CI_BUILDS_DIR
    GIT_CLONE_PATH: $CI_BUILDS_DIR/src/bitbucket.org/rj/goey
    DISPLAY: ":1"
    APT_GET: "libgtk-3-dev xvfb"
  script:
    - go get -v bitbucket.org/rj/goey/base bitbucket.org/rj/goey/loop
    - go get -v bitbucket.org/rj/goey/example/...
    - go build -v bitbucket.org/rj/goey bitbucket.org/rj/goey/example/...
    - go test ./base ./loop ./dialog .
  parallel:
    matrix:
      - GOVERSION: ["1.8", "1.9", "1.10"]
        DUMMY: ["dummy"]

golang-js:
  image: "golang:${GOVERSION}"
  stage: build
  variables:
    APT_GET: "chromium"
    GOOS: js
    GOARCH: wasm
    GOBIN: $CI_BUILDS_DIR/bin
  script:
    - GOOS= GOARCH= go get github.com/agnivade/wasmbrowsertest@latest
    - GOOS= GOARCH= go install github.com/agnivade/wasmbrowsertest
    - ln $GOBIN/wasmbrowsertest $GOBIN/go_js_wasm_exec
    - PATH=$PATH:$GOBIN
    - go build -v . ./example/...
    - go test -v -run Test ./base ./loop .
  parallel:
    matrix:
      - GOVERSION: ["1.14", "latest"]
        DUMMY: ["dummy"]

golang-windows:
  stage: build
  tags:
    - windows
    - windows-1809
  before_script:
    - go version
  script:
    - go build . ./example/...
    - go test ./base ./loop . -v

golang-cocoa:
  image: "golang:${GOVERSION}"
  stage: build
  variables:
    DISPLAY: ":1"
    APT_GET: "gnustep-devel xvfb"
  script:
    - go build -v -tags cocoa . ./example/...
    - go test -v -tags cocoa ./base ./loop .
  parallel:
    matrix:
      - GOVERSION: ["1.12", "latest"]
        DUMMY: ["dummy"]

test-gtk:
  image: golang:latest
  stage: test
  needs: []
  variables:
    GOPATH: $CI_BUILDS_DIR
    GIT_CLONE_PATH: $CI_BUILDS_DIR/src/bitbucket.org/rj/goey
    DISPLAY: ":1"
    APT_GET: "libgtk-3-dev xvfb"
    SCREENSHOTS: "onebutton twofields decoration colour"
  before_script:
    - *before_script_all
    - mkdir -p .cache/github.com
    - mv .cache/github.com $GOPATH/src/
  after_script:
    - mv $GOPATH/src/github.com .cache/
  script:
    - go get bitbucket.org/rj/goey bitbucket.org/rj/goey/example/...
    - go test -coverprofile=cover-gtk.out -v ./base ./loop ./dialog .
    - go tool cover -html=cover-gtk.out -o=cover.html
    - go test -v -race ./loop 
    - go vet -composites=false ./base ./loop ./dialog .
    - go get -u github.com/gordonklaus/ineffassign
    - go install github.com/gordonklaus/ineffassign
    - $GOPATH/bin/ineffassign .
    - go get -u github.com/client9/misspell/cmd/misspell
    - go install github.com/client9/misspell/cmd/misspell
    - $GOPATH/bin/misspell -locale US *.go *.md base/*.go loop/*.go dialog/*.go
    - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin v2.2.0
    - $GOPATH/bin/gosec -exclude-dir=internal -exclude=G104,G204,G304 ./...
    - mkdir ./images
    - for elem in $SCREENSHOTS; do go build -v bitbucket.org/rj/goey/example/$elem; done
    - for elem in $SCREENSHOTS; do GOEY_SCREENSHOT=./images/${elem}_linux.png ./$elem; done
  cache:
    key: test
    paths:
      - .cache/github.com/
  except:
    - tags
  artifacts:
    paths:
      - cover.html
      - cover-gtk.out
      - images/

test-windows:
  image: golang:latest
  stage: test
  needs: []
  variables:
    DISPLAY: ":1"
    APT_GET: "wine64 wine-binfmt xvfb"
    GOOS: windows
  script:
    - go get bitbucket.org/rj/goey bitbucket.org/rj/goey/example/...
    - go build bitbucket.org/rj/goey bitbucket.org/rj/goey/example/...
    - go test -c -coverprofile=cover.out ./base
    - wine64 ./base.test.exe -test.coverprofile=cover.out -test.v
    - go test -c -coverprofile=cover.out ./loop
    - wine64 ./loop.test.exe -test.coverprofile=cover.out -test.v
    - go test -c -coverprofile=cover.out .
    - wine64 ./goey.test.exe -test.coverprofile=cover.out -test.v -test.short
    - go tool cover -html=cover.out -o=cover.html
  except:
    - tags
  artifacts:
    paths:
      - cover.html

test-cocoa:
  image: golang:latest
  stage: test
  needs: []
  variables:
    DISPLAY: ":1"
    APT_GET: "gnustep-devel xvfb fluxbox"
  script:
    - fluxbox 2> nul &
    - go test -tags cocoa -coverprofile=cover-cocoa.out -v ./base ./loop .
    - go tool cover -html=cover-cocoa.out -o=cover.html
    - go test -tags cocoa -v -race ./loop 
  except:
    - tags
  artifacts:
    paths:
      - cover.html
      - cover-cocoa.out

lint:
  image: golang:latest
  stage: test
  needs: []
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- v1.40.0
    - ./bin/golangci-lint run -v --enable-all --disable wsl --issues-exit-code=0 .
  except:
    - tags
  allow_failure: true

pages:
  stage: deploy
  dependencies:
    - test-gtk
  script:
    - mkdir ./public
    - mv cover.html ./public
    - mv images/*.png ./public
  only:
    - master
  artifacts:
    paths:
      - public

